### ISSUE TITLE
Error: Cannot find module '/usr/bin/lib/node_modules/git-issues/index.js'

### ISSUE THREAD

**Issue by Temeez** [softwarescales/git-issues#11]
I installed this normally via npm ```sudo npm install -g git-issues``` and spits this error when I try to use it in a git project directory.

Centos 7
npm 1.3.6
node 0.10.36

```
$ git issues

module.js:340
    throw err;
          ^
Error: Cannot find module '/usr/bin/lib/node_modules/git-issues/index.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

```
$ sudo find -iname git-issues
./root/.npm/git-issues
./root/.npm/git-issues/0.7.0/package/bin/git-issues
./usr/bin/git-issues
./usr/lib/node_modules/git-issues
./usr/lib/node_modules/git-issues/bin/git-issues

```

**Comment by IonicaBizau** [comment]
It looks like [this path](https://github.com/softwarescales/git-issues/blob/d73b98a25ce7a7f47ca71c3b13e5a49d3bdb97a2/bin/git-issues#L21) is not correctly computed.

I'm not sure how easy is to fix it, but this could be fixed very simple with a nodejs script.

In the meantime you can hack it and hardcode the path in `/usr/lib/node_modules/git-issues/bin/git-issues`:

```sh
node /usr/lib/node_modules/git-issues $@ --repo "$GIT_URL"
```

I guess it should work.

**Comment by IonicaBizau** [comment]
I'm on it.
