### ISSUE TITLE
Cache user & password or access token into a file

### ISSUE THREAD

**Issue by IonicaBizau** [softwarescales/git-issues#7]
It would be so good if the user and password were cached into a json config file.
I imagine the following scenario.

A file named `~/.git-issues-config.json` that contains:

```json
{
    "username": "..."
  , "password": "..."
}
```

or

```json
{
    "accessToken": "..."
}
```

...where access token can be generated [here](https://github.com/settings/tokens/new).

**Comment by Tobi3112** [comment]
Hey, nice work! I noticed that the file ".git-issues-config.json-"  in your repository does not have the correct path:)

**Comment by IonicaBizau** [comment]
@Tobi3112 Thanks! :joy: Addressed in https://github.com/softwarescales/git-issues/commit/77069a40d723dfa04ffd13abb481c463b97f12c9.
